### ISSUE TITLE
limma normalization per 10xLane

### ISSUE THREAD

**Issue by bio-la** [kotliary/baseline#1]
Hi, your paper is really great!
i'm analysing some data generated over 3 channels/lanes of a 10x Chip. I am normalizing each channel-worth of ADT data with your DSB package, as the background is channel-specific. I need to merge these 3 channels in one dataset afterwards. how can i address the batch effect that the 3 different normalizations would probably introduce? in the paper you mention using limma

> In addition, to account for droplet-to-droplet differences in the ADT capture rate as well as background noise from unbound antibody, we denoised each cell by removing a covariate corresponding to the background counts for each cell using the removeBatchEffect function in limma

can you clarify when and how this normalization is applied? before or after merging your channels (i suppose your data is over 6 channels from the methods but I'm unsure).

thank you!

**Comment by kotliary** [comment]
Hi @bio-la, Thanks for your interest in our paper. I would advise to ask @MattPM. He was the one who developed and performed the normalization. This is the same method that implemented now in his dsb package.
