### ISSUE TITLE
Question on contents of the `H1_day0_demultilexed_singlets.RDS` file

### ISSUE THREAD

**Issue by sorjuela** [kotliary/baseline#2]
Hi @kotliary , 

I downloaded the file `H1_day0_demultilexed_singlets.RDS` and I'm trying to follow your code to build my own SingleCellExperiment, but I'm a bit confused of which rows are the surface markers and which are genes:

You start by loading and splitting by batch,
```
# read in final singlets make list of seurat objects indexed by batch. 
h1 = readRDS(file = "data/H1_day0_demultilexed_singlets.RDS") %>% SetAllIdent(id = "batch")
h1b1 = SubsetData(h1, ident.use = "1")
h1b2 = SubsetData(h1, ident.use = "2")
```
Then you use `h1b1` and `h1b2` as your positive ADT counts
```
# make list of positive protein matrices by batch 
stained = list(h1b1, h1b2)
pos_adt = lapply(stained, function(x){x@assay$CITE@raw.data})
```
then you use the same `h1b1` and `h1b2` to analyze the RNA data
```
sc = list(h1b1, h1b2)
sc =  lapply(sc, function(x){ Convert(from = x, to = "sce") })  
suppressMessages(library(scater))
sc = lapply(sc, FUN = calculateQCMetrics)
```

I don't understand what part of the seurat object has the RNA and what part the ADT.

Thank you,
Stephany

**Comment by kotliary** [comment]
Hi Stephany,
Thank you for your interest in our data.

Seurat object is S4  object with the data located in slots that you can access with @ operator.
RNA data are located in `h1@raw.data`, `h1@data`, etc.
Meta-data for all cells are in `h1@meta.data`.
ADT data are from additional assay and are stored in assay slot, which is a list of multiple Seurat objects. You can access ADT raw data as `h1@assay$CITE@raw.data`.

Hope it helps.
Yuri
